[package]
name = "srm"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.39", features = ["serde"] }
dirs = "5.0.1"
glob = "0.3.2"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.135"
sha256 = "1.5.0"
thiserror = "2.0.11"
